version: "3.8"

# if we were to add to external sevices porvided by other docker-compose file
# networks:
#   default:
#     external:
#       name: my-interservice-network

services:
  echo-server:
    build: .
    ports:
      - "5000:5000"
    tty: true
    command:
      watchdog auto-restart --patterns "*.py" --recursive -- python3 echo.py && \
      wait-for-it --service database:5432 -- python3 echo.py # runs python echo.py only after database:5432 is available
    volumes:
      - .:/app/
    environment:
      - DATABASE_HOME = database
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD = password
    depends_on: # makes sure that echo-server will be started after database service
      - database 

  database:
    image: postgres:13.1
    restart: always

    environment:
      - POSTGRES_PASSWORD=password

  cache:
    image: redis:6.0.8
